name: streamlit-docker-build

on:
  push:
    branches:
      - "main"
    paths:
    - Dockerfile
    - main.py
    - .github/workflows/docker-build.yaml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker
        run: | 
          docker build -t mdh266/speechimage:cloudrun .
          docker push mdh266/speechimage:cloudrun 
