name: streamlit-docker-deploy

env:
  SERVICE_NAME: speech2image
  DOCKER_IMAGE: mdh266/speechimage

on:
  push:
    branches:
      - "main"
    paths:
    - Dockerfile
    - main.py
    - .github/workflows/docker-build.yaml

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: | 
          ruff format main.py
          ruff check main.py

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker
        run: | 
          docker build -t ${{ env.DOCKER_IMAGE }}:cloudrun .
          docker push ${{ env.DOCKER_IMAGE }}:cloudrun 

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
    
      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy $SERVICE_NAME \
            --image=${{ env.DOCKER_IMAGE }}:cloudrun \
            --set-env-vars=REPLICATE_API_TOKEN=${{ secrets.REPLICATE_API_TOKEN }},GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
            --region=us-central1 \
            --project=${{ secrets.GOOGLE_PROJECT_ID }} 
